CAN-2168 horovod params description
IntelAI/nauta-zoo pull request #7
Opened 2019-05-20 13:48 UTC by mateusz-ciesielski

* Add description to parameters in values.yaml
* Add recommended MKL env variables for increased training performance

2019-06-04 12:23 UTC, mateusz-ciesielski commented
Tests:
https://ci.nervana.sclab.intel.com/job/carbon/job/k8s/job/K8sClusterOps-builder01/371/

2019-06-04 12:33 UTC, mzylowski approved these changes

2019-06-06 10:12 UTC, jcchr requested changes

2019-06-06 10:12 UTC, jcchr commented on jupyter/charts/values.yaml
> +# Resorce settings
Resource

2019-06-06 10:12 UTC, jcchr commented on multinode-tf-training-horovod-py2/charts/values.yaml
> +      value: "granularity=fine,verbose,compact,1,0"  # these are reccomended affinity settings
recommended

2019-06-06 10:12 UTC, jcchr commented on multinode-tf-training-horovod-py2/charts/values.yaml
> +      value: "granularity=fine,verbose,compact,1,0"  # these are reccomended affinity settings
recommend

2019-06-06 10:12 UTC, jcchr commented on multinode-tf-training-horovod/charts/values.yaml
> +      value: "granularity=fine,verbose,compact,1,0"  # these are reccomended affinity settings
recommended

2019-06-06 10:12 UTC, jcchr commented on multinode-tf-training-horovod/charts/values.yaml
> +      value: "granularity=fine,verbose,compact,1,0"  # these are reccomended affinity settings
recommended

2019-06-06 10:12 UTC, jcchr commented on multinode-tf-training-tfjob-py2/charts/values.yaml
> +# Resorce settings for training workers
resource

2019-06-06 10:12 UTC, jcchr commented on multinode-tf-training-tfjob-py2/charts/values.yaml
> +    value: "granularity=fine,verbose,compact,1,0"  # these are reccomended affinity settings
recommended

2019-06-06 10:12 UTC, jcchr commented on multinode-tf-training-tfjob/charts/values.yaml
> +# Resorce settings for training workers
resource

2019-06-06 10:12 UTC, jcchr commented on multinode-tf-training-tfjob/charts/values.yaml
> +# Resorce settings for parameter servers
resource

2019-06-06 10:12 UTC, jcchr commented on multinode-tf-training-tfjob/charts/values.yaml
> +    value: "granularity=fine,verbose,compact,1,0"  # these are reccomended affinity settings
recommended

2019-06-06 10:12 UTC, jcchr commented on pytorch/charts/values.yaml
> +# Resorce settings for training workers
resource

2019-06-06 10:12 UTC, jcchr commented on pytorch/charts/values.yaml
> +# Resorce settings for master
resource

2019-06-06 10:12 UTC, jcchr commented on tf-inference-batch/charts/values.yaml
> +# Resorce settings for batch inference instance
resource

2019-06-06 10:12 UTC, jcchr commented on tf-inference-batch/charts/values.yaml
> +# Resorce settings for batch inference wrapper
resource

2019-06-06 10:12 UTC, jcchr commented on tf-inference-stream/charts/values.yaml
> +# Resorce settings for stream inference instance
resource

2019-06-06 10:12 UTC, jcchr commented on tf-training-tfjob-py2/charts/values.yaml
> +# Resorce settings for training pod
resource

2019-06-06 10:12 UTC, jcchr commented on tf-training-tfjob-py2/charts/values.yaml
> +    value: "granularity=fine,verbose,compact,1,0"  # these are reccomended affinity settings
recommend

2019-06-06 10:12 UTC, jcchr commented on tf-training-tfjob/charts/values.yaml
> +    value: "granularity=fine,verbose,compact,1,0"  # these are reccomended affinity settings
recommend

2019-06-10 12:21 UTC, mateusz-ciesielski commented
@jcchr Typos fixed

2019-07-02 13:23 UTC, jcchr requested changes

2019-07-02 13:23 UTC, jcchr commented on tf-training-tfjob-py2/charts/values.yaml
> +  - name: OMP_NUM_THREADS
tf-training-tfjob is not a multinode training - so it doesn't use OpenMPI - thus those variables are superfluous here.

2019-07-02 13:23 UTC, jcchr commented on tf-training-tfjob/charts/values.yaml
> +  - name: OMP_NUM_THREADS
tf-training-tfjob is not a multinode training - so it doesn't use OpenMPI - thus those variables are superfluous here.

2019-07-02 13:23 UTC, jcchr commented on multinode-tf-training-tfjob-py2/charts/values.yaml
> +  - name: OMP_NUM_THREADS
In this pack we don't use OpenMPI - so those variables are not needed.

2019-07-02 13:23 UTC, jcchr commented on multinode-tf-training-tfjob/charts/values.yaml
> +  - name: OMP_NUM_THREADS
In this pack we don't use OpenMPI - so those variables are not needed.

2019-07-19 09:49 UTC, mateusz-ciesielski commented
@jcchr 
According to https://www.tensorflow.org/guide/performance/overview#tuning_mkl_for_the_best_performance `OMP_NUM_THREADS` is used by MKL (so not only OpenMPI) for performance tuning

2019-07-22 08:45 UTC, jcchr approved these changes

2019-07-22 11:37 UTC, mateusz-ciesielski commented
Tests:
https://ci.nervana.sclab.intel.com/job/carbon/job/k8s/job/K8sClusterOps/13632/

2019-07-25 13:07 UTC, merged